site_name: 'Bayesian Modeling'
site_description: 'The'
docs_dir: 'docs/src'

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

theme:
    name: 'material'