site_name: 'Bayesian Modeling'
site_description: 'The'
site_author: 'Al-Ahmadgaid B. Asaad'
site_url: 'https://bayesmodeling.github.io/'

docs_dir: 'docs/src'

repo_name: 'GitHub'
repo_url: 'https://github.com/bayesmodeling/bayesmodeling.github.io'

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

extra:
  social:
    - type: 'github'
      link: 'https://github.com/squidfunk'
    - type: 'twitter'
      link: 'https://twitter.com/squidfunk'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/squidfunk'

theme:
    name: 'material'